doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            bigserial:  Doctrine\DBAL\Types\BigIntType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                date_part: DoctrineExtensions\Query\Postgresql\DatePart
                extract: DoctrineExtensions\Query\Postgresql\ExtractFunction
                age: DoctrineExtensions\Query\Postgresql\Age
                date: DoctrineExtensions\Query\Postgresql\Date
            string_functions:
                str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
                count_filter: DoctrineExtensions\Query\Postgresql\CountFilterFunction
                string_agg: DoctrineExtensions\Query\Postgresql\StringAgg
                greatest: DoctrineExtensions\Query\Postgresql\Greatest
                least: DoctrineExtensions\Query\Postgresql\Least
                regexp_replace: DoctrineExtensions\Query\Postgresql\RegexpReplace
